version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6179:6379"
    command: redis-server --requirepass 1405 --maxmemory 1gb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    volumes:
      - ./redis-master-data:/data
    networks:
      - redis-net

  redis-slave-1:
    image: redis:latest
    container_name: redis-slave-1
    ports:
      - "6279:6379"
    command: redis-server --requirepass 1405 --maxmemory 1gb --maxmemory-policy allkeys-lru --slaveof redis-master 6179
    networks:
      - redis-net

  redis-slave-2:
    image: redis:latest
    container_name: redis-slave-2
    ports:
      - "6379:6379"
    command: redis-server --requirepass 1405 --maxmemory 1gb --maxmemory-policy allkeys-lru --slaveof redis-master 6179
    networks:
      - redis-net

  redis-sentinel-1:
    image: redis:latest
    container_name: redis-sentinel-1
    ports:
      - "26179:26379"
    command: redis-sentinel /redis-master-sentinel.conf
    volumes:
      - ./sentinel.conf:/redis-master-sentinel.conf
    networks:
      - redis-net
    depends_on:
      - redis-master

  redis-sentinel-2:
    image: redis:latest
    container_name: redis-sentinel-2
    ports:
      - "26279:26379"
    command: redis-sentinel /redis-master-sentinel.conf
    volumes:
      - ./sentinel.conf:/redis-master-sentinel.conf
    networks:
      - redis-net
    depends_on:
      - redis-master

  redis-sentinel-3:
    image: redis:latest
    container_name: redis-sentinel-3
    ports:
      - "26379:26379"
    command: redis-sentinel /redis-master-sentinel.conf
    volumes:
      - ./sentinel.conf:/redis-master-sentinel.conf
    networks:
      - redis-net
    depends_on:
      - redis-master

networks:
  redis-net:
    driver: bridge
